server:
  port: 8891
spring:
  cloud:
    config:
      server:
        git:
          uri: ssh://git@github.com/gdcollectdata/iMakerBot-BackendEnd.git
          default-label: main
          passphrase: 'ahmed'
          clone-on-start: true
          search-paths: imaker-proprietes
      enabled: true
      override-system-properties: true
